name: mpox_analyse
channels:
  - conda-forge
  - bioconda
dependencies:
  # Téléchargement des données
  - sra-tools>=3.0
  # QC & nettoyage
  - fastqc>=0.12
  - fastp>=0.23
  - multiqc>=1.20
  - nanoplot>=1.42
  - chopper
  # Alignement (Illumina + Nanopore)
  - bowtie2>=2.5
  - minimap2>=2.26
  - samtools>=1.19
  # Variants & consensus
  - bcftools>=1.19
  - bedtools>=2.31
  - clair3
  # Assemblage de novo
  - spades>=3.15
  - blast